### ISSUE TITLE
error while installing using yarn: cannot use 'in' operator 

### ISSUE THREAD

**Issue by chiptus** [joshmatz/big-bertha#9]
I get the following error:
warning big-bertha > forever > forever-monitor > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
error TypeError: Cannot use 'in' operator to search for '^2.1.0-0' in undefined
    at C:\Users\One\AppData\Roaming\npm\node_modules\yarn\lib\resolvers\registries\npm-resolver.js:62:24
    at next (native)
    at step (C:\Users\One\AppData\Roaming\npm\node_modules\yarn\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
    at C:\Users\One\AppData\Roaming\npm\node_modules\yarn\node_modules\babel-runtime\helpers\asyncToGenerator.js:35:14
    at Promise.F (C:\Users\One\AppData\Roaming\npm\node_modules\yarn\node_modules\core-js\library\modules_export.js:35:28)
    at C:\Users\One\AppData\Roaming\npm\node_modules\yarn\node_modules\babel-runtime\helpers\asyncToGenerator.js:14:12
    at Function.findVersionInRegistryResponse (C:\Users\One\AppData\Roaming\npm\node_modules\yarn\lib\resolvers\registries\npm-resolver.js:72:7)
    at C:\Users\One\AppData\Roaming\npm\node_modules\yarn\lib\resolvers\registries\npm-resolver.js:89:34
    at next (native)
    at step (C:\Users\One\AppData\Roaming\npm\node_modules\yarn\node_modules\babel-runtime\helpers\asyncToGenerator.js:17:30)
info Visit http://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by joshmatz** [comment]
It looks like this may have been related to the DNS issues that were plaguing the Internet last week, according to yarnpkg/yarn#1348. Does this still occur for you?
